// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
	"domain"
        "contract"
)

var _ = domain.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  ReturnType AddPatient( identifier,  name,  contact, AdministrativeGender gender, i32 birthDate,  address, bool issueMR)")
  fmt.Fprintln(os.Stderr, "   FindPatientByIdentifier(Identifier identifier)")
  fmt.Fprintln(os.Stderr, "  Patient FindPatientById(string id)")
  fmt.Fprintln(os.Stderr, "  Patient FindPatientByName(string name)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := contract.NewBaseServiceClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "AddPatient":
    if flag.NArg() - 1 != 7 {
      fmt.Fprintln(os.Stderr, "AddPatient requires 7 args")
      flag.Usage()
    }
    arg15 := flag.Arg(1)
    mbTrans16 := thrift.NewTMemoryBufferLen(len(arg15))
    defer mbTrans16.Close()
    _, err17 := mbTrans16.WriteString(arg15)
    if err17 != nil { 
      Usage()
      return
    }
    factory18 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt19 := factory18.GetProtocol(mbTrans16)
    containerStruct0 := contract.NewBaseServiceAddPatientArgs()
    err20 := containerStruct0.ReadField1(jsProt19)
    if err20 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Identifier
    value0 := argvalue0
    arg21 := flag.Arg(2)
    mbTrans22 := thrift.NewTMemoryBufferLen(len(arg21))
    defer mbTrans22.Close()
    _, err23 := mbTrans22.WriteString(arg21)
    if err23 != nil { 
      Usage()
      return
    }
    factory24 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt25 := factory24.GetProtocol(mbTrans22)
    containerStruct1 := contract.NewBaseServiceAddPatientArgs()
    err26 := containerStruct1.ReadField2(jsProt25)
    if err26 != nil {
      Usage()
      return
    }
    argvalue1 := containerStruct1.Name
    value1 := argvalue1
    arg27 := flag.Arg(3)
    mbTrans28 := thrift.NewTMemoryBufferLen(len(arg27))
    defer mbTrans28.Close()
    _, err29 := mbTrans28.WriteString(arg27)
    if err29 != nil { 
      Usage()
      return
    }
    factory30 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt31 := factory30.GetProtocol(mbTrans28)
    containerStruct2 := contract.NewBaseServiceAddPatientArgs()
    err32 := containerStruct2.ReadField3(jsProt31)
    if err32 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.Contact
    value2 := argvalue2
    arg33 := flag.Arg(4)
    mbTrans34 := thrift.NewTMemoryBufferLen(len(arg33))
    defer mbTrans34.Close()
    _, err35 := mbTrans34.WriteString(arg33)
    if err35 != nil {
      Usage()
      return
    }
    factory36 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt37 := factory36.GetProtocol(mbTrans34)
    argvalue3 := domain.NewAdministrativeGender()
    err38 := argvalue3.Read(jsProt37)
    if err38 != nil {
      Usage()
      return
    }
    value3 := argvalue3
    tmp4, err39 := (strconv.Atoi(flag.Arg(5)))
    if err39 != nil {
      Usage()
      return
    }
    argvalue4 := int32(tmp4)
    value4 := argvalue4
    arg40 := flag.Arg(6)
    mbTrans41 := thrift.NewTMemoryBufferLen(len(arg40))
    defer mbTrans41.Close()
    _, err42 := mbTrans41.WriteString(arg40)
    if err42 != nil { 
      Usage()
      return
    }
    factory43 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt44 := factory43.GetProtocol(mbTrans41)
    containerStruct5 := contract.NewBaseServiceAddPatientArgs()
    err45 := containerStruct5.ReadField6(jsProt44)
    if err45 != nil {
      Usage()
      return
    }
    argvalue5 := containerStruct5.Address
    value5 := argvalue5
    argvalue6 := flag.Arg(7) == "true"
    value6 := argvalue6
    fmt.Print(client.AddPatient(value0, value1, value2, value3, value4, value5, value6))
    fmt.Print("\n")
    break
  case "FindPatientByIdentifier":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FindPatientByIdentifier requires 1 args")
      flag.Usage()
    }
    arg47 := flag.Arg(1)
    mbTrans48 := thrift.NewTMemoryBufferLen(len(arg47))
    defer mbTrans48.Close()
    _, err49 := mbTrans48.WriteString(arg47)
    if err49 != nil {
      Usage()
      return
    }
    factory50 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt51 := factory50.GetProtocol(mbTrans48)
    argvalue0 := domain.NewIdentifier()
    err52 := argvalue0.Read(jsProt51)
    if err52 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.FindPatientByIdentifier(value0))
    fmt.Print("\n")
    break
  case "FindPatientById":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FindPatientById requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.FindPatientById(value0))
    fmt.Print("\n")
    break
  case "FindPatientByName":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FindPatientByName requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.FindPatientByName(value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
